import os

# API access tokens
SMARTSHEET_ACCESS_TOKEN = os.getenv("SMARTSHEET_ACCESS_TOKEN")
BOX_ACCESS_TOKEN = os.getenv("BOX_ACCESS_TOKEN")

# Smartsheet settings
SMARTSHEET_EPR_TRACKER_TABLE_ID = 2190844477001604  # Used for EPR Tracker webhook
SMARTSHEET_SEPARATIONS_TRACKER_TABLE_ID = 6507921459335044  # Used for Separations webhook
SMARTSHEET_VACANCIES_TABLE_ID = 4963448636002180

# Box settings
BOX_DEN_UPLOAD_FOLDER_ID = 369360455196  # Used for Vacancies webhook

# AWS API Gateway Webhook addresses
EPR_TRACKER_API_GATEWAY_ADDRESS = os.getenv("EPR_TRACKER_API_GATEWAY_ADDRESS")
SEPARATIONS_API_GATEWAY_ADDRESS = os.getenv("SEPARATIONS_API_GATEWAY_ADDRESS")
VACANCIES_API_GATEWAY_ADDRESS = os.getenv("VACANCIES_API_GATEWAY_ADDRESS")
