import os
from pathlib import Path

# Settings
STAGE_DEV = "DEV"
STAGE_PROD = "PROD"
STAGE = os.getenv("SBPD_STAGE", STAGE_DEV)

# API ACCESS TOKENS
SMARTSHEET_ACCESS_TOKEN = os.getenv("SMARTSHEET_ACCESS_TOKEN")

# Smartsheet settings
SMARTSHEET_VACANCIES_TABLE_ID = os.getenv("SMARTSHEET_VACANCIES_TABLE_ID")

# Box.com settings
BOX_ACCESS_TOKEN = os.getenv("BOX_ACCESS_TOKEN")
BOX_DEN_UPLOAD_FOLDER_ID = 369360455196
BOX_USED_DEN_FILES_FOLDER_ID = 369359846105

# Other settings